version: '3.4'

services:
  webapplication1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
     # - "65391:80"

  webapplication3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
     # - "52153:80"

